language: node_js
node_js:
  - '6'
cache: yarn
install:
  - chmod +x scripts/*.sh
script: npm run test-travis
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: benjamin.otto@style-systems.de
  api_key:
    secure: srNFQ8cHP65FUiQ1cQn5pBTvNyftxozAj03IgDxXGVvaFL5zSBlubqvsVyJXkjoE3lA0218lL2MbXZGimHFPkEXBIjITlOJcv9QSmxuGvz3T1CChtJucZTreK3tRZ6MnuJADRVMiIZqswgzEPTtVODNLdcFB8PfOqrGv4hk4Qt+/5iCSIdU6p8ZXU/yAVWg+jol02h2jKQX7vP8jceRlUJVLH/i1ePmb/c+wlVbHUwoG9U9I+vP5IN7y98RH8VznEzTyWDf7Z278SsDqMa3kc9v4lO5quN31IvR4jHzKYw6+Kh37DF8OC7J3RIXv08KmqZFYHr8ouJ/ftVTw3E6YkfU4abaRXNgt8d4xdthLSS17g6B7S0R+EyU9tHzfAANTPQ0WQ9aqCZOEPG9s+qRZzpmbLzZkXXHCIOCu//PprO4ZE2aFcKuTT/IZVQ3RnK1VGySf/hd94B2O4XDHLZeiKKtXiCMF2MS65o6xNgnih14Dj2CwaWNP6numRrCoDKpC5W5Yavmq+UomowH5I7/EH10mnWBWS3iCZVO5TeBGEc7yLHxiquT2fv6v3CMMR46qzlX8Eq0UYc/or5iow+BotHjrHGmW+JarG7vFhOZpXX6xnhcFZXb7Q/NiujDyhAM/cmn718HbU1gWH/+O3ktwFtzuIMqNrda0IwbFuszqk6g=
  on:
    tags: true
    repo: otbe/profilr
